version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: avalon_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: avalon
    networks:
      - avalon-net

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - avalon-net

volumes:
  mongodb_data:

networks:
  avalon-net:
    driver: bridge
