services:
  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile

    ports:
      - '80:80'

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile

    ports:
      - '3000:3000'
