version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: avalon_mongodb
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - avalon-net

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - avalon-net

volumes:
  mongodb_data:

networks:
  avalon-net:
    driver: bridge
