name: Publish images to Docker Hub

concurrency:
  group: docker-publish
  cancel-in-progress: true

on:
  push:
    tags: [v*.*.*]

jobs:
  # Publish backend image
  publish-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build and publish container in Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          file: backend.Dockerfile
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/backend-avalon:${{ github.ref_name }}

  # Publish ui image
  publish-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build and publish container in Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ui.Dockerfile
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/nginx-avalon:${{ github.ref_name }}
